export const DEFAULT_PARTS = [
  { name: "Connector", category: "PIPE" },
  { name: "Pipe (01 mit)", category: "PIPE" },
  { name: "Switch", category: "ELECTRICAL" },
  { name: "Tap", category: "OTHER" },
  { name: "Ro cover", category: "OTHER" },
  { name: "Flow", category: "OTHER" },

  { name: "PP filter (120g)", category: "FILTER" },
  { name: "PP 3micro", category: "FILTER" },
  { name: "PP thread", category: "FILTER" },
  { name: "Sediment", category: "FILTER" },
  { name: "Carbon", category: "FILTER" },
  { name: "Membrane", category: "FILTER" },
  { name: "High TDS membrane", category: "FILTER" },
  { name: "Mineral cartridge", category: "FILTER" },
  { name: "UF Filter cartridge", category: "FILTER" },
  { name: "ORG UF alkaline", category: "FILTER" },
  { name: "ORG UF Membrane", category: "FILTER" },
  { name: "Copper filter", category: "FILTER" },
  { name: '20" inch pp', category: "FILTER" },
  { name: '20" carbon', category: "FILTER" },
  { name: "Jambo bag", category: "FILTER" },
  { name: "Jambo pp", category: "FILTER" },

  { name: "D.v set", category: "OTHER" },
  { name: "Solenoid valve (sv)", category: "ELECTRICAL" },
  { name: "Membrane housing", category: "OTHER" },
  { name: "Bucket pump", category: "ELECTRICAL" },
  { name: "Pre-filter housing", category: "OTHER" },
  { name: "C & X clamp", category: "OTHER" },
  { name: "Cut of cock", category: "OTHER" },
  { name: "Smps", category: "ELECTRICAL" },
  { name: "Motor (pump)", category: "ELECTRICAL" },
  { name: "Tank inlet fish", category: "OTHER" },
  { name: "TDS adjuster", category: "OTHER" },
  { name: "UV strip light", category: "ELECTRICAL" },
  { name: "UV tube", category: "ELECTRICAL" },
  { name: "UV chamber", category: "ELECTRICAL" },
  { name: "UV chock", category: "ELECTRICAL" },
  { name: "A.s. par Tablet", category: "OTHER" },
];
